steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/web-map-console/Dockerfile'
      - '--build-arg'
      - 'VITE_API_BASE_URL='
      - '--build-arg'
      - 'VITE_MAP_STYLE_URL=https://demotiles.maplibre.org/style.json'
      - '--build-arg'
      - 'VITE_MAP_CENTER_LNG=115.1889'
      - '--build-arg'
      - 'VITE_MAP_CENTER_LAT=-8.4095'
      - '--build-arg'
      - 'VITE_MAP_ZOOM=9'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/time-rally-navigator/timerally/web:latest'
      - '.'

images:
  - 'asia-southeast2-docker.pkg.dev/time-rally-navigator/timerally/web:latest'
