steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/web-map-console/Dockerfile'
      - '--build-arg'
      - 'VITE_API_BASE_URL='
      - '--build-arg'
      - 'VITE_MAP_STYLE_URL=/maps/bali-style.json'
      - '--build-arg'
      - 'VITE_MAP_FALLBACK_STYLE_URL=https://demotiles.maplibre.org/style.json'
      - '--build-arg'
      - 'VITE_PMTILES_URL=https://storage.googleapis.com/timerally-bali-maps/maps/bali.pmtiles'
      - '--build-arg'
      - 'VITE_PMTILES_READY=true'
      - '--build-arg'
      - 'VITE_MAP_CENTER_LNG=115.2126'
      - '--build-arg'
      - 'VITE_MAP_CENTER_LAT=-8.6705'
      - '--build-arg'
      - 'VITE_MAP_ZOOM=13'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/time-rally-navigator/timerally/web:latest'
      - '.'

images:
  - 'asia-southeast2-docker.pkg.dev/time-rally-navigator/timerally/web:latest'
